apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: o1g5jhz6j-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o1g5jhz6j-nodejs 
  name: o1g5jhz6j-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: o1g5jhz6j-nodejs
    weight: 100 
