apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o1g5jhz6j-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o1g5jhz6j-nodejs 
  name: o1g5jhz6j-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: o1g5jhz6j-nodejs 
